<a href="https://colab.research.google.com/github/DJohanTwT/DataV24/blob/main/C2_Clase_4___Data_Structure.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Guardar más de un valor

# **1. What is a DS**
A variable that stores a *value sequence*.

One example: List (variable que tiene una secuencia de datos que serian los nombres de una clase), arrays (is a vector), tuplets, database.

# **2. Linear Algebra**
(para hacer operaciones matematicas)

## **2.1. Numpy**

Numpy (numerical python) is a library that perform operationes in data structures. Meaning, it does linear algebra.

In [2]:
import numpy

In [3]:
numpy.array([1,2,3])

array([1, 2, 3])

In [4]:
import numpy as np #Standard nickname - se le puede poner un nombre a la libreria

In [5]:
np.array([1,2,3])

array([1, 2, 3])

## **2.2. Numpy arrays - Vectors and Matrices**

In [6]:
# Column vector
a = np.array([[1],[2],[3]])  #[] Brackets, separa los rows - columnas
print(a)
print(a.shape) #valor.shape #shape is the dimension of the vector

[[1]
 [2]
 [3]]
(3, 1)


In [14]:
# Row vector
b = np.array([4,5,6]) #commas separates the columns
print(b)
print(b.shape)

[4 5 6]
(3,)


In [8]:
# Squared Matrix
A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(A)
print(A.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


tupple es un elemento con dos datos

In [9]:
s = A.shape
print(s) #se imprime el tuple en una linea

n, m = A.shape #se imprime el tuple en dos lineas separadas usando la coma
print('Number of rows',n)
print('Number of columns',m)

(3, 3)
Number of rows 3
Number of columns 3


In [10]:
## WARNING!!!
x = 2
y = np.array([[2]])
print(type(x)) #int - numero entero
print(type(y)) #objeto con dimensiones - si da ese error es porque esta pidiendo el valor con brackets
#No es lo mismo sin y con brackets

<class 'int'>
<class 'numpy.ndarray'>


## **2.3. Slicing**
Cortar o extraer cosas. Acceder información de los vectores.

In [16]:
# Extract one element

print(A[0,0]) #elemento fila 1 columna 1. Extract the element in row 1 column 1
print(a[1,0]) #Extract the element in row 2 column 1
print(b[1]) #Extract the element in row 1 column 2

1
2
5


In [18]:
# A little trick

print(A[-1,-1]) #Last element | Trae el ultimo elemento que es 9.
print(A[-2,-2]) #penultima fila y penultima columna

9
5


In [19]:
# Extract a subset
print(A[0:2, 1:3]) #trae desde la fila 0 a la 1 (que son 1 y 2). Trae la columna 1 a la 3 (que son 1 y 2)

[[2 3]
 [5 6]]


In [20]:
# Extract the whole row
print(A[0,:])

[1 2 3]


In [23]:
# Extract the whole column
print(A[:,0])

[1 4 7]
